### ISSUE TITLE
Just call the functions directly no need for a function whose only purpose it so call a function.

### ISSUE THREAD

**Issue by C0BBL3** [RileyPaddock/space-empires#36]
You have 3 functions, `complete_movement_phase`, `complete_combat_phase`, and `complete_economic_phase`, which only call their respective functions, just call the function directly in your complete turn.

**Comment by RileyPaddock** [comment]
I like it more this way because if you look in the engine each of those functions is a little long and has logs and stuff in it and putting all of that in one function would be very nasty. This way I can just clearly say I am completing the phase and if you want to see what happens then you can go to the engine. I think this way is cleaner and it doesn't hurt my code in any way.
